CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  Jscs:
    enabled: false

  ScssLint:
    enabled: false

  JsHint:
    enabled: false

  AuthorEmail:
    enabled: false

  AuthorName:
    enabled: false

  MergeConflicts:
    enabled: true

  TrailingWhitespace:
    enabled: true
    exclude: ['vendor/**/*', 'spec/docs/v1/docs.md']

  BundleOutdated:
    enabled: true

  ExecutePermissions:
    enabled: false

  ForbiddenBranches:
    enabled: true
    branch_patterns: ['master']

  LineEndings:
    enabled: true
    exclude: ['spec/fixtures/**/*']

  RailsSchemaUpToDate:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  Rubocop:
    enabled: true

  Fasterer:
    enabled: true

  # BundleAudit:
  #   enabled: true

  RailsBestPractices:
    enabled: true

  HamlLint:
    enabled: true
