require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-i18n

RSpec/MessageChain:
  Enabled: false

RSpec/FilePath:
  Exclude:
  - 'spec/concepts/**/**/*'

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
    - 'app/admin/*'

RSpec/ContextWording:
  Exclude:
    - 'spec/models/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 121

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/views/**/*'

AllCops:
  Exclude:
    - 'bin/*'
    - '*.gemspec'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
  TargetRubyVersion: 2.6.3
